# Generated by Django 3.2.8 on 2021-10-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20211014_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idClient',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='idProducto',
            field=models.IntegerField(default=0),
        ),
    ]
