# Generated by Django 3.2.8 on 2021-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_auto_20211014_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='idClient',
            new_name='idUser',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Admon', 'Admon')], default='Cliente', max_length=100),
        ),
    ]
