# Generated by Django 3.2.8 on 2021-10-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20211015_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idProducto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='idUser',
            field=models.IntegerField(),
        ),
    ]
