# Generated by Django 3.2.8 on 2021-10-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_auto_20211015_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idProducto',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='idUser',
            field=models.IntegerField(default=1),
        ),
    ]
