# Generated by Django 3.2.8 on 2021-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_auto_20211015_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unidadesTotales',
            field=models.IntegerField(default=0),
        ),
    ]
