# Generated by Django 3.2.8 on 2021-10-19 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_product_unidadestotales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(max_length=100, verbose_name='Rol'),
        ),
    ]
