# Generated by Django 3.2.8 on 2021-10-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_auto_20211019_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='order',
            name='idProducto',
            field=models.ManyToManyField(to='authApp.Product'),
        ),
    ]
