# Generated by Django 3.2.8 on 2021-10-26 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_auto_20211022_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='idProducto',
        ),
        migrations.CreateModel(
            name='ListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.order')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.product')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
