# Generated by Django 3.2.8 on 2021-10-26 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0010_auto_20211025_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='idUser',
            new_name='idUsuario',
        ),
    ]
