# Generated by Django 3.2.8 on 2021-10-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_rename_iduser_order_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
